# Generated by Django 4.0.6 on 2022-07-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('sobrenome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=250)),
                ('salaCafe', models.CharField(max_length=200)),
                ('lotacao', models.DecimalField(decimal_places=0, max_digits=350)),
                ('lotacaoCafe', models.DecimalField(decimal_places=0, max_digits=350)),
                ('pessoas', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
