# Generated by Django 4.0.6 on 2022-07-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_remove_sala_pessoas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='pessoas',
            field=models.CharField(default='', max_length=255),
        ),
    ]
