# Generated by Django 4.0.6 on 2022-07-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_sala_pessoas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaReuniao', models.CharField(max_length=250)),
                ('salaCafe', models.CharField(max_length=200)),
                ('pessoa', models.CharField(max_length=200)),
            ],
        ),
    ]
